#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify /sysroot/.nestos-aleph-version.json exists.

# Defined in https://github.com/coreos/fedora-coreos-tracker/blob/master/internals/README-internals.md#aleph-version

set -xeuo pipefail

# shellcheck disable=SC1091
. "$KOLA_EXT_DATA/commonlib.sh"

jq . < /sysroot/.nestos-aleph-version.json >/dev/null
ok aleph
