# This file is most of a NestOS like system; it inherits from "core".
# Add things in this file which are somewhat "opinionated", not necessarily
# core functionality.

include:
  - ignition-and-ostree.yaml
  - file-transfer.yaml
  - networking-tools.yaml
  - system-configuration.yaml
  - user-experience.yaml
  - shared-workarounds.yaml
  - bootupd.yaml

# Be minimal
recommends: false

ignore-removed-users:
  - root
ignore-removed-groups:
  - root
etc-group-members:
  - wheel
  - sudo
  - systemd-journal
  - adm

check-passwd:
  type: "file"
  filename: "passwd"
check-groups:
  type: "file"
  filename: "group"

default-target: multi-user.target

# we can drop this when it's the rpm-ostree default
rpmdb: sqlite

# ⚠⚠⚠ ONLY TEMPORARY HACKS ALLOWED HERE; ALL ENTRIES NEED TRACKER LINKS ⚠⚠⚠
# See also the version of this in nestos.yaml
postprocess:
  - |
    #!/usr/bin/env bash
    systemctl mask kdump.service
    systemctl mask mdmonitor.service

  # https://gitee.com/openeuler/nestos-config/issues/I5R05H?from=project-issue
  - |
    #!/usr/bin/env bash
    rm -rf /usr/lib/locale/locale-archive
    cp /usr/lib/locale/locale-archive.default /usr/lib/locale/locale-archive 

  # Mask dnsmasq. We include dnsmasq for host services that use the dnsmasq
  # binary but intentionally mask the systemd service so users can't easily
  # use it as an external dns server. We prefer they use a container for that.
  - |
    #!/usr/bin/env bash
    systemctl mask dnsmasq.service

packages:
  - kernel
  # Security
  - polkit
  # Containers
  - systemd-container catatonit
  - fuse-overlayfs slirp4netns
  # support for old style CNI networks and name resolution for
  # podman containers with CNI networks
  # https://github.com/coreos/fedora-coreos-tracker/issues/519
  # https://github.com/coreos/fedora-coreos-tracker/issues/1128#issuecomment-1071338097
  - containernetworking-plugins podman-plugins dnsmasq
  # Since we need `containernetworking-plugins` installed to continue
  # to support CNI networks we need to also explicitly install
  # `netavark` so we get both of them installed since both of them
  # provide `container-network-stack`.
  # https://github.com/coreos/fedora-coreos-tracker/issues/1128#issuecomment-1071458717
  - netavark
  # Minimal NFS client
  - nfs-utils-min
  # Active Directory support
  - adcli
  # WireGuard https://github.com/coreos/fedora-coreos-tracker/issues/362
  - wireguard-tools
  # Storage
  - btrfs-progs
  - WALinuxAgent-udev
  # Allow communication between sudo and SSSD
  # for caching sudo rules by SSSD.
  # https://github.com/coreos/fedora-coreos-tracker/issues/445
  - libsss_sudo
  # SSSD; we only ship a subset of the backends
  - sssd-client sssd-ad sssd-ipa sssd-krb5 sssd-ldap
  # Used by admins interactively
  - attr
  - openssl
  # Provides terminal tools like clear, reset, tput, and tset
  - ncurses
  # file-transfer: note fuse-sshfs is not in RHEL
  # so we can't put it in file-transfer.yaml
  - fuse-sshfs
  # Improved MOTD experience
  - console-login-helper-messages-motdgen
  # i18n
  - kbd
  # zram-generator (but not zram-generator-defaults) for F33 change
  # https://github.com/coreos/fedora-coreos-tracker/issues/509
  - zram-generator
  # This thing is crying out to be pulled into systemd, but that hasn't happened
  # yet.  Also we may want to add to rpm-ostree something like arch negation;
  # https://serverfault.com/questions/513807/is-there-still-a-use-for-irqbalance-on-modern-hardware
  # https://access.redhat.com/solutions/41535
  - irqbalance