
packages:
  # Basic user tools
  ## jq - parsing/interacting with JSON data
  - bash-completion
  - coreutils
  - jq
  - wget
  - less
  - sudo
  - vim-minimal
  # File compression/decompression
  ## bsdtar - dependency of 35nestos-live dracut module
  - bsdtar
  - bzip2
  - gzip
  - tar
  - xz
  - zstd
  # Improved MOTD experience
  - console-login-helper-messages-issuegen
  - console-login-helper-messages-profile
  # kdump support
  - kexec-tools
  # Remote Access
  - openssh-clients openssh-server
  # Container tooling
  - podman
  - skopeo
  - toolbox
  - crun
  # enable k8s
  - libnetfilter_cthelper
  - libnetfilter_cttimeout
  - libnetfilter_queue
  - conntrack-tools
  - isula-build
