# This file is most of a NestOS like system; it inherits from "core".
# Add things in this file which are somewhat "opinionated", not necessarily
# core functionality.

include:
  - ignition-and-ostree.yaml
  - system-configuration.yaml
  - user-experience.yaml
  - bootupd.yaml
  - rpmlist.yaml

# Be minimal
recommends: false

ignore-removed-users:
  - root
ignore-removed-groups:
  - root
etc-group-members:
  - wheel
  - sudo
  - systemd-journal
  - adm

check-passwd:
  type: "file"
  filename: "passwd"
check-groups:
  type: "file"
  filename: "group"

default-target: multi-user.target

# we can drop this when it's the rpm-ostree default
rpmdb: sqlite

# ⚠⚠⚠ ONLY TEMPORARY HACKS ALLOWED HERE; ALL ENTRIES NEED TRACKER LINKS ⚠⚠⚠
# See also the version of this in nestos.yaml
postprocess:
  - |
    #!/usr/bin/env bash
    systemctl mask kdump.service
    systemctl mask mdmonitor.service

  # https://gitee.com/openeuler/nestos-config/issues/I5R05H?from=project-issue
  - |
    #!/usr/bin/env bash
    rm -rf /usr/lib/locale/locale-archive
    cp /usr/lib/locale/locale-archive.default /usr/lib/locale/locale-archive 

  # Mask dnsmasq. We include dnsmasq for host services that use the dnsmasq
  # binary but intentionally mask the systemd service so users can't easily
  # use it as an external dns server. We prefer they use a container for that.
  - |
    #!/usr/bin/env bash
    systemctl mask dnsmasq.service

  # Some services require /etc/issue.d dir, which is pre created here
  - |
    #!/usr/bin/env bash
    mkdir /etc/issue.d
