# These are packages that are related to configuring parts of the system.
# It is intended to be kept generic.

postprocess:
  # Mask systemd-repart. Ignition is responsible for partition setup on first
  # boot and does not use systemd-repart currently. See also
  # https://github.com/coreos/fedora-coreos-tracker/issues/570
  - |
    #!/usr/bin/env bash
    systemctl mask systemd-repart.service
